MyApp\Domain\Owner:
    type: entity
    table: owner
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
# /**
#  * @ORM\Entity(repositoryClass="\MyApp\Bundle\ProductBundle\Owner\Repository\OwnerRepository")
#  * @ORM\Table(name="owner")
#  */
#  /**
#   * @ORM\Column(type="integer")
#   * @ORM\Id
#   * @ORM\GeneratedValue(strategy="AUTO")
#   */
#   /**
#    * @ORM\Column(type="string", length=100)
#    */