#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

product_create:
  path: /product/
  defaults: { _controller: AppBundle:CreateProduct:execute }
  methods: [POST]

product_delete:
  path: /product/{id}/
  defaults: { _controller: AppBundle:DeleteProduct:execute }
  methods: [DELETE]

product_update:
  path: /product/{id}/
  defaults: { _controller: AppBundle:UpdateProduct:execute }
  methods: [POST]

product_list:
  path: /product/
  defaults: { _controller: AppBundle:ListProducts:execute }
  methods: [GET]