#app:
#    resource: "@ProductBundle/Controller/"
#    type:     annotation

product_create:
  path: /product/
  defaults: { _controller: ProductBundle:Product:create }
  methods: [POST]

product_delete:
  path: /product/{id}/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Controller\DeleteProductController::execute }
  methods: [DELETE]

product_update:
  path: /product/{id}/
  defaults: { _controller: ProductBundle:Product:update }
  methods: [PUT]

product_list:
  path: /product/
  defaults: { _controller: ProductBundle:Product:show }
  methods: [GET]

owner_list:
  path: /owner/
  defaults: { _controller: ProductBundle:Owner:show }
  methods: [GET]

owner_create:
  path: /owner/
  defaults: { _controller: ProductBundle:Owner:create }
  methods: [POST]
