#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#homepage:
#  path: /
#  defaults: { _controller: AppBundle:Default:index }
#
#constraint:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:paramConstraint }
#  requirements:
#    param: '\d+'
#
#param_homepage:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:param }

request_querystring:
  path: /querystring/
  defaults: { _controller: AppBundle:Default:requestQuerystring }

request_post:
  path: /post/
  defaults: { _controller: AppBundle:Default:requestPost }
  methods: [POST]

request_querystring2:
  path: /querystring2/
  defaults: { _controller: MyApp:Bundle:Default:requestQuerystring }

request_post2:
  path: /post2/
  defaults: { _controller: MyApp:Bundle:Default:requestPost }
  methods: [POST]