# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:

    # _defaults:
    #     autowire: true
    #     autoconfigure: true
    #     public: false

    myapp.repository.owner:
        class: MyApp\Bundle\ProductBundle\Owner\Repository\MySQLOwnerRepository
        public: true
        arguments:
            - "@doctrine.orm.default_entity_manager"
# services:



#     app.owner.repository:
#         class: MyApp\Bundle\ProductBundle\Owner\Repository\MySqlOwnerRepository
#         public: false
#         arguments:
#             - "@doctrine.orm.default_entity_manager"