# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:

    # _defaults:
    #     autowire: true
    #     autoconfigure: true
    #     public: false

    myapp.repository.owner:
        class: MyApp\Bundle\ProductBundle\Owner\Repository\MySQLOwnerRepository
        public: false
        arguments:
            - "@doctrine.orm.default_entity_manager"
    myapp.repository.product:
        class: MyApp\Bundle\ProductBundle\Product\Repository\MySQLProductRepository
        public: false
        arguments:
            - "@doctrine.orm.default_entity_manager"
    myapp.command.handler.create.owner:
        class: MyApp\Application\CommandHandler\Owner\CreateOwnerCommandHandler
        public: true
        arguments:
            - "@myapp.repository.owner"
    myapp.command.handler.show.owners:
        class: MyApp\Application\CommandHandler\Owner\ListOwnersCommandHandler
        public: true
        arguments:
            - "@myapp.repository.owner"
    myapp.command.handler.show.products:
        class: MyApp\Application\CommandHandler\Product\ListProductsCommandHandler
        public: true
        arguments:
            - "@myapp.repository.product"
