<?php

namespace MyApp\Bundle\AppBundle\Repository\UnaEntity;

/**
 * EstoQueEsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstoQueEsRepository extends \Doctrine\ORM\EntityRepository
{
}
